#define WIFI_SSID <WIFI_SSID>
#define WIFI_PASSWORD <WIFI_PASSWORD>

#define MQTT_HOST <MQTT_HOST>
#define MQTT_PORT <MQTT_PORT>

#define MQTT_PUB_TOPIC <MQTT_PUB_TOPIC>

#define DHTPIN <DHTPIN>
#define DHTTYPE <DHT11 || DHT22>

#define SEALEVELPRESSURE_HPA (1013.25)